# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'

- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'specific'
    itemPattern: '**/build/libs/*jar'
    downloadPath: '$(System.ArtifactsDirectory)'


- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Pipeline.Workspace)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '804dc0c7-7146-409b-87fd-c5329cee2671'
    vstsFeedPackagePublish: 'shib-authn3'
    versionOption: 'patch'