# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarCloudAnalyze@1

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarQube'
    organization: 'nqtech'
    scannerMode: 'Other'

- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '2.6.1'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/build/distributions/'
    artifact: 'shib-oxauth-authn3'
    publishLocation: 'pipeline'